# URL for frontend
cURL = "https://project-rio-frontend.vercel.app"

#Rio Web Version
cRIO_WEB_VERSION = "1.0.0"

# Dicts to interpret result of play
cPLAY_RESULT_INVLD = {0: 'Strike/Foul'}
cPLAY_RESULT_OUT  = {
    1: 'Strikeout',
    4: 'Out',
    5: 'Caught',
    6: 'Caught', 
    0xE: 'SacFly'
}
cPLAY_RESULT_SAFE = {
    2: 'BB', 
    3: 'HBP', 
    7: 'Single', 
    8: 'Double',
    9: 'Triple',
    0xA: 'Homerun',
    0x10: 'ClearedBases'
}
cPLAY_RESULT_BUNT = {0xD: 'Bunt'}

# Consts used to create profile query
cCharacters = 1
cCaptains = 2

cDefaultEloRating = 1500
cDefaultEloRd = 300
cDefaultEloVol = 0.06

cTYPE_OF_SWING = {
    0: "None",
    1: "Slap",
    2: "Charge",
    3: "Star",
    4: "Bunt"
}

cTAG_TYPES = {
    0: "Component",
    1: "Competition",
    3: "Community",
    4: "Client Code",
    5: "Gecko Code",
    6: "Test"
}

cTAG_SET_TYPES = {
    0: "Season",
    1: "League",
    3: "Tournament",
    4: "Custom",
    5: "Test"
}

cCOMM_TYPES = {
    0: "Official",
    1: "Unofficial",
}

cGAMES = {
    "GYQE01": "MarioSuperstarBaseball",
    "GFTE01": "MarioGolfToadstoolTour"
}

cPATREON_TIERS = ['Patron: Fan', 'Patron: Rookie', 'Patron: MVP', 'Patron: Hall of Famer']

cACTIVE_TAGSET_LIMIT = 5


cCHAR_ALIASES = {
    "Mario": 0,
    "Luigi": 1,
    "DK" : 2,
    "DonkeyKong" : 2,
    "Diddy": 3,
    "DiddyKong": 3,
    "Peach": 4,
    "Daisy": 5,
    "Yoshi": 6,
    "BabyMario" : 7,
    "BabyLuigi": 8,
    "Bowser": 9,
    "Wario": 10,
    "Waluigi": 11,
    "Koopa(G)": 12,
    "GreenKoopa": 12,
    "GreenKoopaTroopa": 12,
    "Toad(R)" : 13,
    "ToadRed" : 13,
    "RedToad" : 13,
    "Toad" : 13,
    "Boo" : 14,
    "Toadette": 15,
    "ShyGuy(R)" : 16,
    "ShyGuyRed" : 16,
    "RedShyGuy" : 16,
    "RedGuy" : 16,
    "RSG" : 16,
    "ShyGuy" : 16,
    "Birdo": 17,
    "Monty": 18,
    "MontyMole": 18,
    "Bowser Jr": 19,
    "BJ": 19,
    "Bowser Junior": 19,
    "Paratroopa(R)": 20,
    "KoopaParatroopaRed": 20,
    "RedKoopaParatroopa": 20,
    "ParaRed": 20,
    "RedPara": 20,
    "PTRed": 20,
    "RedPT": 20,
    "Pianta(B)": 21,
    "PiantaBlue": 21,
    "BluePianta": 21,
    "BlueBlob": 21,
    "BB": 21,
    "Pianta(R)": 22,
    "PiantaRed": 22,
    "RedPianta": 22,
    "PM": 22,
    "Pianta(Y)": 23,
    "PiantaYellow": 23,
    "YellowPianta": 23,
    "YellaFella": 23,
    "Noki(B)": 24,
    "NokiBlue": 24,
    "BlueNoki": 24,
    "Noki(R)": 25,
    "NokiRed": 25,
    "RedNoki": 25,
    "Noki": 26,
    "Noki(G)": 26,
    "NokiGreen": 26,
    "GreenNoki": 26,
    "MintNoki": 26,
    "Bro(H)": 27,
    "Hammerbro": 27,
    "Hammer": 27,
    "H!Bro": 27,
    "HBro": 27,
    "Toadsworth": 28,
    "TW": 28,
    "PeteRose": 28,
    "Toad(B)" : 29,
    "ToadBlue" : 29,
    "BlueToad" : 29,
    "Toad(Y)" : 30,
    "ToadYellow" : 30,
    "YellowToad" : 30,
    "Toad(G)" : 31,
    "ToadGreen" : 31,
    "GreenToad" : 31,
    "Toad(P)" : 32,
    "ToadPurple" : 32,
    "PurpleToad" : 32,
    "Magikoopa(B)": 33,
    "MagikoopaBlue": 33,
    "BlueMagikoopa": 33,
    "MagBlue": 33,
    "BlueMag": 33,
    "MageBlue": 33,
    "BlueMage": 33,
    "Magikoopa(R)": 34,
    "MagikoopaRed": 34,
    "RedMagikoopa": 34,
    "MagRed": 34,
    "RedMag": 34,
    "MageRed": 34,
    "RedMage": 34,
    "Magikoopa(G)": 35,
    "MagikoopaGreen": 35,
    "GreenMagikoopa": 35,
    "MagGreen": 35,
    "GreenMag": 35,
    "MageGreen": 35,
    "GreenMage": 35,
    "Magikoopa(Y)": 36,
    "MagikoopaYellow": 36,
    "YellowMagikoopa": 36,
    "MagYellow": 36,
    "YellowMag": 36,
    "MageYellow": 36,
    "YellowMage": 36,
    "PissWizard": 36,
    "King Boo": 37,
    "KBoo": 37,
    "KB": 37,
    "PeteyPirahana": 38,
    "Petey": 38,
    "DixieKong": 39,
    "Dixie": 39,
    "Goomba": 40,
    "Paragoomba": 41,
    "ParaG": 41,
    "PG": 41,
    "Koopa(R)": 42,
    "Koopa": 42,
    "KoopaTroopa": 42,
    "RedKoopa": 42,
    "RedKoopaTroopa": 42,
    "KoopaRed": 42,
    "KoopaTroopaRed": 42,
    "Rafa": 42,
    "Rafael": 42,
    "Paratroopa(G)": 43,
    "KoopaParatroopaGreen": 43,
    "GreenKoopaParatroopa": 43,
    "ParaGreen": 43,
    "GreenPara": 43,
    "PTGreen": 43,
    "GreenPT": 43,
    "Para": 43,
    "ParaT": 43,
    "PT": 43,
    "ShyGuy(B)" : 44,
    "ShyGuyBlue" : 44,
    "BlueShyGuy" : 44,
    "BlueGuy" : 44,
    "BSG" : 44,
    "ShyGuy(Y)" : 45,
    "ShyGuyYellow" : 45,
    "BlueShyYellow" : 45,
    "YellowGuy" : 45,
    "YSG" : 45,
    "ShyGuy(G)" : 47,
    "ShyGuyGreen" : 47,
    "GreenShyGuy" : 47,
    "GreenGuy" : 47,
    "GSG" : 47,
    "ShyGuy(Bk)" : 48,
    "ShyGuyBlack" : 48,
    "BlackShyGuy" : 48,
    "BlackGuy" : 48,
    "BlSG" : 48,
    "DryBones(Gy)" : 49,
    "DryBones" : 49,
    "Bones" : 49,
    "DryBonesGray" : 49,
    "DryBonesGrey" : 49,
    "GreyDryBones" : 49,
    "GrayDryBones" : 49,
    "BonesGray" : 49,
    "BonesGrey" : 49,
    "GreyBones" : 49,
    "GrayBones" : 49,
    "DryBones(G)" : 50,
    "DryBonesGreen" : 50,
    "GreenDryBones" : 50,
    "BonesGreen" : 50,
    "GreenBones" : 50,
    "DryBones(R)" : 51,
    "DryBonesRed" : 51,
    "RedDryBones" : 51,
    "BonesRed" : 51,
    "RedBones" : 51,
    "DryBones(B)" : 52,
    "DryBonesBlue" : 52,
    "BlueDryBones" : 52,
    "BonesBlue" : 52,
    "BlueBones" : 52,
    "Bro(F)": 53,
    "Fire": 53,
    "Firebro": 53,
    "F!Bro": 53,
    "FBro": 53,
    "Bro(B)": 54,
    "Boomerbro": 54,
    "Boomer": 54,
    "B!Bro": 54,
    "BBro": 54,
}
