"""empty message

Revision ID: 04759bce64a7
Revises: 317a0dde3cfd
Create Date: 2023-04-17 19:30:28.026493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04759bce64a7'
down_revision = '317a0dde3cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_history', 'winner_elo', nullable=False, new_column_name='winner_incoming_elo')
    op.alter_column('game_history', 'loser_elo', nullable=False, new_column_name='loser_incoming_elo')
    op.add_column('game_history', sa.Column('winner_result_elo', sa.Integer(), nullable=True))
    op.add_column('game_history', sa.Column('loser_result_elo', sa.Integer(), nullable=True))
    op.add_column('game_history', sa.Column('recalced_elo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_history', 'winner_incoming_elo', nullable=False, new_column_name='winner_elo')
    op.alter_column('game_history', 'loser_incoming_elo', nullable=False, new_column_name='loser_elo')
    op.drop_column('game_history', 'recalced_elo')
    op.drop_column('game_history', 'loser_result_elo')
    op.drop_column('game_history', 'winner_result_elo')
    # ### end Alembic commands ###
