"""empty message

Revision ID: 5e820ba37623
Revises: 8734a6a139e8
Create Date: 2023-03-27 22:52:51.005126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e820ba37623'
down_revision = '8734a6a139e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_tag')
    op.drop_table('user')
    op.alter_column('ongoing_game', 'away_roster_0_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'away_roster_1_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'away_roster_2_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'away_roster_3_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'away_roster_4_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'away_roster_5_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'away_roster_6_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'away_roster_7_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'away_roster_8_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'home_roster_0_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'home_roster_1_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'home_roster_2_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'home_roster_3_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'home_roster_4_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'home_roster_5_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'home_roster_6_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'home_roster_7_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ongoing_game', 'home_roster_8_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ongoing_game', 'home_roster_8_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'home_roster_7_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'home_roster_6_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'home_roster_5_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'home_roster_4_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'home_roster_3_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'home_roster_2_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'home_roster_1_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'home_roster_0_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'away_roster_8_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'away_roster_7_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'away_roster_6_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'away_roster_5_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'away_roster_4_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'away_roster_3_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'away_roster_2_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'away_roster_1_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ongoing_game', 'away_roster_0_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('username_lowercase', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('rio_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('active_url', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('active_url', name='user_active_url_key'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('rio_key', name='user_rio_key_key'),
    sa.UniqueConstraint('username', name='user_username_key'),
    sa.UniqueConstraint('username_lowercase', name='user_username_lowercase_key')
    )
    op.create_table('game_tag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change_requested', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], name='game_tag_game_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='game_tag_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_tag_pkey')
    )
    # ### end Alembic commands ###
