"""Add game column to TagSet and Tag

Revision ID: de5a48158561
Revises: de7d5b19d918
Create Date: 2024-08-05 21:06:26.306703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5a48158561'
down_revision = 'de7d5b19d918'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game', sa.String(length=50), nullable=True))

    with op.batch_alter_table('tag_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game', sa.String(length=50), nullable=True))

    # Populate existing rows with "GAME1"
    op.execute("UPDATE tag SET game='GYQE01' WHERE game IS NULL")
    op.execute("UPDATE tag_set SET game='GYQE01' WHERE game IS NULL")

    # Alter the column to be non-nullable
    with op.batch_alter_table('tag_set', schema=None) as batch_op:
        batch_op.alter_column('game', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_set', schema=None) as batch_op:
        batch_op.drop_column('game')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('game')
    # ### end Alembic commands ###
