"""Remove ranked column from game table

Revision ID: f354f1a77f46
Revises: de7d5b19d918
Create Date: 2026-05-31 11:39:30.826577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f354f1a77f46'
down_revision = 'de7d5b19d918'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('ranked')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranked', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.create_table('wpa_game_state_map',
    sa.Column('score_out_inning_state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_score_diff_adjustment', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_score_diff_adjustment', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inning_adjustment', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('half_inning', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('outs', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('vertical_trajectories',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_trajectory', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('swing_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pitch_type_1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pitch_type_2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('stick_input', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bucket_0_upper_randomsum', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_1_upper_randomsum', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_2_upper_randomsum', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_3_upper_randomsum', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_4_upper_randomsum', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_0_chance_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_1_chance_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_2_chance_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_3_chance_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_4_chance_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_0_vertdegree_range_lower', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_1_vertdegree_range_lower', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_2_vertdegree_range_lower', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_3_vertdegree_range_lower', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_4_vertdegree_range_lower', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_0_vertdegree_range_upper', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_1_vertdegree_range_upper', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_2_vertdegree_range_upper', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_3_vertdegree_range_upper', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bucket_4_vertdegree_range_upper', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vertical_trajectories_pkey')
    )
    # ### end Alembic commands ###
